# Generated by Django 5.2.4 on 2025-07-17 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_borrowedbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowedBook',
        ),
    ]
